cd woff2
./woff2_compress ttf/OverusedGrotesk-Light.ttf
./woff2_compress ttf/OverusedGrotesk-LightItalic.ttf
./woff2_compress ttf/OverusedGrotesk-Book.ttf
./woff2_compress ttf/OverusedGrotesk-BookItalic.ttf
./woff2_compress ttf/OverusedGrotesk-Roman.ttf
./woff2_compress ttf/OverusedGrotesk-Italic.ttf
./woff2_compress ttf/OverusedGrotesk-Medium.ttf
./woff2_compress ttf/OverusedGrotesk-MediumItalic.ttf
./woff2_compress ttf/OverusedGrotesk-SemiBold.ttf
./woff2_compress ttf/OverusedGrotesk-SemiBoldItalic.ttf
./woff2_compress ttf/OverusedGrotesk-Bold.ttf
./woff2_compress ttf/OverusedGrotesk-BoldItalic.ttf
./woff2_compress ttf/OverusedGrotesk-ExtraBold.ttf
./woff2_compress ttf/OverusedGrotesk-ExtraBoldItalic.ttf
./woff2_compress ttf/OverusedGrotesk-Black.ttf
./woff2_compress ttf/OverusedGrotesk-BlackItalic.ttf
